/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.15";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -I/usr/local/include -O2 -Wall";
const char *link_string = "gcc -O2 -Wall -liconv -lnettle -L/usr/local/lib -lgnutls -lz ftp-opie.o gnutls.o http-ntlm.o ../lib/libgnu.a";
